development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379").sub(%r{/\d+\z}, "") %>/4
  channel_prefix: galaseason_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379").sub(%r{/\d+\z}, "") %>/4
  channel_prefix: galaseason_production
